name: lab8_414539

on:
  push:
    branches:
      - trunk-lab8

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run:  |
          pip install numpy pytest
      - name: Run unit tests
        run: |
          cd ./env_414539/main
          pytest calculator_test.py -k "test_dodawanie or test_odejmowanie or test_mnozenie or test_dzielenie"
  run_functional_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run:  |
          cd ./env_414539/main
          python -m pip install -r requirements.txt
      - name: Run Flask server
        run: |
          export FLASK_APP = ./env_414539/main/app_test.py
          flask run & sleep 5
      - name: Run functional tests
        run: |
          cd ./env_414539/main
          pytest app_test.py -k "test_calculator_operations"

